server:
  port: 8080
spring:
  application:
    name: e17-spring-boot-cloud-server
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:mysql://localhost:3306/e16_spring_cloud
    username: root
    password: rootroot
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log